os: linux

language: php

before_script:
  - composer self-update

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

# optionally set up exclutions and allowed failures in the jobs
jobs:
  allow_failures:
    - php: 7.4
    

install:
 - composer install --dev

script:
  - mkdir -p var
  - php bin/phpunit -c travis.phpunit.xml


after_script:
  - php vendor/bin/coveralls
