<?php

namespace Etechnika\IdnaConvert;

use Etechnika\IdnaConvert\TranscodeWrapper;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-16 at 16:59:14.
 *
 * @covers Etechnika\IdnaConvert\TranscodeWrapper
 */
class TranscodeWrapperTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TranscodeWrapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TranscodeWrapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Etechnika\IdnaConvert\TranscodeWrapper::encode_utf8
     * @todo   Implement testEncodeUtf8().
     */
    public function testEncodeUtf8()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\IdnaConvert\TranscodeWrapper::decode_utf8
     * @todo   Implement testDecodeUtf8().
     */
    public function testDecodeUtf8()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\IdnaConvert\TranscodeWrapper::map_w1252_iso8859_1
     * @todo   Implement testMapW1252Iso88591().
     */
    public function testMapW1252Iso88591()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Etechnika\IdnaConvert\TranscodeWrapper::map_iso8859_1_w1252
     * @todo   Implement testMapIso88591W1252().
     */
    public function testMapIso88591W1252()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
